name: StatSync
version: '0.1.17-SNAPSHOT'
main: org.asylum_media.statsync.StatSync
api-version: '1.21'
authors: [ Asylum_Media ]
description: Data parser for PaperMC server staff use.
softdepend:
  - BeanSync
  - AfkSync
  - Floodgate
  - SessionStats
  - PlayerStats
  - UJobs
  - PunisherX
commands:
  statsync:
    description: Resolve and sync target player stats
    usage: /statsync context <player>
    permission: statsync.use
permissions:
  statsync.use:
    default: op
